### ISSUE TITLE
VSS add-on coordination (mapping)

### ISSUE THREAD

**Issue by erikbosch** [COVESA/data-expert-group#11]
_This is a topic originating from the Porto AMM_

There are multiple initiatives using VSS syntax to add extended attributes. Two examples are KUKSA.val (map DBC to VSS) and COVESA AASIG (map Android VHAL to/from VSS). There is a possibility that a platform/project need to use multiple mappings, and then it is important that there are no name conflicts. 

COVESA could address this by: 

- Providing guidelines, for example that all attributes are to be added under a single "namespace"
- Maintain a list of already taken/used "namespaces".
- Possibly "host" some "namespace" definitions, i.e. the definition of sub-attributes and syntax for them

With this, inspired by the two examples below, it would be possible to include multiple mappings in the same tree (after applying overlays), like:
```

Vehicle.Chassis.SteeringWheel.Angle:
  datatype: int16
  type: sensor
  dbc:
    signal: SteeringAngle129
    interval_ms: 100
    transform:
      math: "floor(x+0.5)"
  vhal:
    aospId: VehicleProperty::PERF_VEHICLE_SPEED
    aospArea: VehicleArea::GLOBAL
    multiplier: 0.27777777777777777777  # (divide by 3.6)
    offset: 0.0
```

**Existing examples:**

https://github.com/COVESA/vss-tools/blob/code_generation/contrib/vspec2aaproperties/vspec2prop_mapping.yml

```
Vehicle.Speed:
  #convertFloatLinear
  aospId: VehicleProperty::PERF_VEHICLE_SPEED
  aospArea: VehicleArea::GLOBAL
  multiplier: 0.27777777777777777777  # (divide by 3.6)
  offset: 0.0
```

https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/mapping/mapping.md
https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/mapping/vss_3.1.1/dbc_overlay.vspec

```
Vehicle.Chassis.SteeringWheel.Angle:
  datatype: int16
  type: sensor
  dbc:
    signal: SteeringAngle129
    interval_ms: 100
    transform:
      math: "floor(x+0.5)"
```
